name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blob-proxy-go
      
    - name: Tag docker with hash
      run: docker tag blob-proxy-go docker.pkg.github.com/newfuture/blob-proxy-go/blob-proxy-go:${GITHUB_SHA::7}
    - name: Tag docker with version and latest, when from release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
           docker tag blob-proxy-go docker.pkg.github.com/newfuture/blob-proxy-go/blob-proxy-go:${GITHUB_REF:10}
           docker tag blob-proxy-go docker.pkg.github.com/newfuture/blob-proxy-go/blob-proxy-go:latest

    - name: login
      run:  docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/newfuture/blob-proxy-go/blob-proxy-go