name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-docker-test:$GITHUB_SHA
      
    - name: Tag
      run: docker tag go-docker-test:$GITHUB_SHA docker.pkg.github.com/newfuture/go-docker/go-docker-test:$GITHUB_SHA
    - name: login
      run:  docker login docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/newfuture/go-docker/go-docker-test:$GITHUB_SHA
